name: hashicorp/packer-plugin-amazon/build_plugin_binaries
permissions:
  contents: read
on:
  push:
    branches:
    - main
jobs:
  build_windows:
    defaults:
      run:
        working-directory: ~/go/src/github.com/hashicorp/packer-plugin-hyperv
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/cimg/go:1.18
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: windows
        GOARCH: 386
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: windows
        GOARCH: amd64
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: linux
        GOARCH: amd64
